sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: b4CYIu219CX0L0RkjYBQi7sAL420LCfL89+46Fk2ufFZEGdPnG9EYROFnTuZ9LM+fJ/I8sktBg65n+dM6rYq4Rl0XBkqWFXi/IivQ8pq87aGClEWhGq/ONGSx74F5B491jRWZWepFfgSXcLmhHIC+hn0OVuqZ6Sg3F+zIwttKCg58cseGHUIwX5GpJeAKNxFwvWwF+gxDiYTLwI7ccVG8CfnYu/SR/IVZSq27ljGxvr3Vjllng5yxmnEnDwp/aWPcRzrav9Nul2MrLi5HXkR28QSt6dLlsvET+WoWNGsGEo8GesVlI64PqXiMZfzrvtGcaoHTJ8gRqhpJLAwIrNwkQQ2zD1dyJVC9pZ9iQoZFDlzrYH9aae1tdA1TfLsxbY4sFfA8oBGNWAY/LnBBCzYvQY52XFMlthxzLgCt/bFStV7o1aAjPmn5GF8nCfAkP6fLOcTwvyeqrX71Etbv0OVWGGfdUl8pW8xdv1v4l9FFKRHvW6i2h/vEAWh5TUEdiezgMp85OybRiw8oBTLh7zcPxMdy2cO3cQ0ah1iN4EGumYyYJviMw2uL2+u1Xx3p2sHfXt425cgc/ikjfoAmXxkDPK68LVS7k4mf0z5Tr0oJrrj+IKMZ7RLVakRhWNcPGNoaTwr0zrjIVU4fTGVcSLlbon230HzO5MVRfAaI8Mjzzs=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: T5cFW7cSRaOyThklifxUQeUXhe3LycpI7eWL/+V2F3aYVYcaO38SXGbDnnONhByy1e43h6wFw4RMubx2rrk6uzqihwaEIJ02lJxnE5jdVa2IEaFTst/IDgyaC29eu/uo5cgwjMH2btEC+xRby56zhfn/Z1uot76M1/RoRfRN2wqOqskIy+2jucEHJlNF1UDy+RauyHzx/DOCK2gEbumqopKWqMfI+4xC1PH0/qxj15HjXr+m2Fqy2lfPDRfmqX+vpJb/FvBsWDROK+jDmP/abKItmtn7/HIDiEhft907tZ6y0jlnUdsQbKegQS3PmNTO1gncr6rvo5Q/b7Et6UI1y6OTB7sPuLH1yaDGcM4WiBfxnNKUjR7Ux7/TdT+pWkwcQo2AGie4oFuih/p2a7lvlg9zIMafNljdys1D1B9xLvzVcJizow4TWTYXffPXjhpfLwR4h0+tUGO3XN0zUKPHi4MiOSyWt4J66O0yHMGs71PpjU0NHJHoswFHvIlsYpGfdTujwCppGXpdug5ihek+BiJyFcTawAHPY7QXVQucuOkPE0Tgz1/SFtm2rYnCKlgEG39tU/aQ3cBJCplP0MLJSnDzRwtldPkNVS/2APrTeu9NvM8jcDAcUE2oR9OfQVUd2mAAohmZtQlvwuMTOCetkXzIAobkky+s4LO2IhAL8vw=
